/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Constancio
 */
public class MenuPetCare extends javax.swing.JFrame{

    /**
     * Creates new form MenuPetCare
     */
    public MenuPetCare(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fmCadastrar = new javax.swing.JMenu();
        miCadastrarPessoa = new javax.swing.JMenuItem();
        miCadastrarRaca = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        fmConsultar = new javax.swing.JMenu();
        miConsultarPessoa = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setLayout(null);

        fmCadastrar.setMnemonic('f');
        fmCadastrar.setText("Cadastrar");

        miCadastrarPessoa.setMnemonic('o');
        miCadastrarPessoa.setText("Pessoa");
        miCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarPessoaActionPerformed(evt);
            }
        });
        fmCadastrar.add(miCadastrarPessoa);

        miCadastrarRaca.setMnemonic('s');
        miCadastrarRaca.setText("Raça");
        miCadastrarRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarRacaActionPerformed(evt);
            }
        });
        fmCadastrar.add(miCadastrarRaca);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("XXXXX");
        fmCadastrar.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("XXXX");
        fmCadastrar.add(exitMenuItem);

        menuBar.add(fmCadastrar);

        fmConsultar.setMnemonic('e');
        fmConsultar.setText("Consultar");

        miConsultarPessoa.setMnemonic('t');
        miConsultarPessoa.setText("Pessoa");
        fmConsultar.add(miConsultarPessoa);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("XXXXXX");
        fmConsultar.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("XXXXXX");
        fmConsultar.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("XXXXX");
        fmConsultar.add(deleteMenuItem);

        menuBar.add(fmConsultar);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Remove todos os desktopPane adicionados anteriormente
     */
    private void closeAllDesktopPane() {
        this.desktopPane.removeAll();
        this.desktopPane.updateUI();
    }
    
    private void miCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarPessoaActionPerformed
        /* Close previous dektopPane added before */
        closeAllDesktopPane();
        CadastroPessoa cadastroPessoaView = new CadastroPessoa();
        cadastroPessoaView.setVisible(true);
        this.desktopPane.add(cadastroPessoaView);
    }//GEN-LAST:event_miCadastrarPessoaActionPerformed

    private void miCadastrarRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarRacaActionPerformed
        /* Close previous dektopPane added before */
        closeAllDesktopPane();
        CadastroRaca cadastroRacaView = new CadastroRaca();
        cadastroRacaView.setVisible(true);
        this.desktopPane.add(cadastroRacaView);
    }//GEN-LAST:event_miCadastrarRacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            for( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ){
                if( "Nimbus".equals( info.getName() ) ){
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch( ClassNotFoundException ex ){
            java.util.logging.Logger.getLogger( MenuPetCare.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch( InstantiationException ex ){
            java.util.logging.Logger.getLogger( MenuPetCare.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch( IllegalAccessException ex ){
            java.util.logging.Logger.getLogger( MenuPetCare.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch( javax.swing.UnsupportedLookAndFeelException ex ){
            java.util.logging.Logger.getLogger( MenuPetCare.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable(){
            public void run(){
                new MenuPetCare().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fmCadastrar;
    private javax.swing.JMenu fmConsultar;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miCadastrarPessoa;
    private javax.swing.JMenuItem miCadastrarRaca;
    private javax.swing.JMenuItem miConsultarPessoa;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    // End of variables declaration//GEN-END:variables

}
